# Generated by Django 3.1.7 on 2021-03-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=50)),
                ('fromdate', models.DateField(max_length=50)),
                ('todate', models.DateField(max_length=50)),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='classmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50)),
                ('syllabus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'classmanage',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.FileField(max_length=200, upload_to='')),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('parentname', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('parentphno', models.CharField(max_length=50)),
                ('parentemailid', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.login')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='testdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.subject')),
            ],
            options={
                'db_table': 'testdetails',
            },
        ),
        migrations.CreateModel(
            name='vaccancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalnoofvaccancy', models.CharField(max_length=50)),
                ('otherinfo', models.CharField(max_length=50)),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.subject')),
            ],
            options={
                'db_table': 'vaccancy',
            },
        ),
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.FileField(max_length=200, upload_to='')),
                ('qualification', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.login')),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('slot', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.subject')),
                ('TUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.tutor')),
            ],
            options={
                'db_table': 'timeatable',
            },
        ),
        migrations.CreateModel(
            name='testresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.student')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.subject')),
                ('TEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.testdetails')),
            ],
            options={
                'db_table': 'testresult',
            },
        ),
        migrations.CreateModel(
            name='subjectallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.subject')),
                ('TUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.tutor')),
            ],
            options={
                'db_table': 'subjectallocation',
            },
        ),
        migrations.CreateModel(
            name='studymaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studymaterial', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.subject')),
            ],
            options={
                'db_table': 'studymaterial',
            },
        ),
        migrations.CreateModel(
            name='staffsalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=50)),
                ('TUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.tutor')),
            ],
            options={
                'db_table': 'staffsalary',
            },
        ),
        migrations.CreateModel(
            name='staffattendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classhour', models.CharField(max_length=50)),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.subject')),
                ('TUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.tutor')),
            ],
            options={
                'db_table': 'staffattendence',
            },
        ),
        migrations.CreateModel(
            name='parentmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.student')),
            ],
            options={
                'db_table': 'parentmessage',
            },
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('notification', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasonforleave', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('TUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.tutor')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='feestructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
            ],
            options={
                'db_table': 'feestructure',
            },
        ),
        migrations.CreateModel(
            name='feereports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalfees', models.CharField(max_length=50)),
                ('feespaid', models.CharField(max_length=50)),
                ('pending', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.student')),
            ],
            options={
                'db_table': 'feereports',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('feedback', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.student')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('complaint', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=90)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.student')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.student')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.tutor')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='CLASS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage'),
        ),
        migrations.CreateModel(
            name='attendenceofstudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('BATCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.batch')),
                ('CLASS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.classmanage')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuiton_app.student')),
            ],
            options={
                'db_table': 'attendenceofstudents',
            },
        ),
    ]
